[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
version = 2

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "Zlib"]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[bans]
external-default-features = "allow"
highlight = "all"
multiple-versions = "deny"
wildcards = "deny"
workspace-default-features = "allow"
